- name: Install maven
  ansible.builtin.yum:
    name: maven
    state: installed

- name: Setup Application
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup

- name: Installing Dependencies
  ansible.builtin.command: mvn clean package
  args:
    chdir: /app

- name: rename jar file
  ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
  args:
    chdir: /app

- name: load schema
  ansible.builtin.import_role:
    name: common
    tasks_from: mysql-schema

- name: Start Application
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd-setup