- name: copy mongodb repo to yum.repos.d
  ansible.builtin.copy:
    src: mongodb.repo
    dest: /etc/yum.repos.d/mongo.repo

- name: Install Mongodb
  ansible.builtin.yum: 
    name: mongodb-org-shell
    state: installed

- name: Load {{component}} data
  ansible.builtin.command: mongo --host mongodb.vijaydeepak0812.online < /app/schema/{{component}}.js